AllCops:
  Includes:
    - lib/*.rb
    - modules/*.rb
    - bin/*.rb
  Excludes:
    - Gemfile
    - spectr.gemspec
Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 17.5

Metrics/LineLength:
  Enabled: true
  Max: 125

Metrics/MethodLength:
  CountComments: false
  Max: 15